//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KorisnickiInterfejs.WSStipendija {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSStipendijaSoap", Namespace="http://tempuri.org/")]
    public partial class WSStipendija : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DajSveStipendijeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajStipendijuOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajSifruStipendijeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSStipendija() {
            this.Url = global::KorisnickiInterfejs.Properties.Settings.Default.KorisnickiInterfejs_WSStipendija_WSStipendija;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DajSveStipendijeCompletedEventHandler DajSveStipendijeCompleted;
        
        /// <remarks/>
        public event DajStipendijuCompletedEventHandler DajStipendijuCompleted;
        
        /// <remarks/>
        public event DajSifruStipendijeCompletedEventHandler DajSifruStipendijeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajSveStipendije", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DajSveStipendije() {
            object[] results = this.Invoke("DajSveStipendije", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DajSveStipendijeAsync() {
            this.DajSveStipendijeAsync(null);
        }
        
        /// <remarks/>
        public void DajSveStipendijeAsync(object userState) {
            if ((this.DajSveStipendijeOperationCompleted == null)) {
                this.DajSveStipendijeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajSveStipendijeOperationCompleted);
            }
            this.InvokeAsync("DajSveStipendije", new object[0], this.DajSveStipendijeOperationCompleted, userState);
        }
        
        private void OnDajSveStipendijeOperationCompleted(object arg) {
            if ((this.DajSveStipendijeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajSveStipendijeCompleted(this, new DajSveStipendijeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajStipendiju", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DajStipendiju(string SIFRA) {
            object[] results = this.Invoke("DajStipendiju", new object[] {
                        SIFRA});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DajStipendijuAsync(string SIFRA) {
            this.DajStipendijuAsync(SIFRA, null);
        }
        
        /// <remarks/>
        public void DajStipendijuAsync(string SIFRA, object userState) {
            if ((this.DajStipendijuOperationCompleted == null)) {
                this.DajStipendijuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajStipendijuOperationCompleted);
            }
            this.InvokeAsync("DajStipendiju", new object[] {
                        SIFRA}, this.DajStipendijuOperationCompleted, userState);
        }
        
        private void OnDajStipendijuOperationCompleted(object arg) {
            if ((this.DajStipendijuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajStipendijuCompleted(this, new DajStipendijuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DajSifruStipendije", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DajSifruStipendije(string naziv) {
            object[] results = this.Invoke("DajSifruStipendije", new object[] {
                        naziv});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DajSifruStipendijeAsync(string naziv) {
            this.DajSifruStipendijeAsync(naziv, null);
        }
        
        /// <remarks/>
        public void DajSifruStipendijeAsync(string naziv, object userState) {
            if ((this.DajSifruStipendijeOperationCompleted == null)) {
                this.DajSifruStipendijeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajSifruStipendijeOperationCompleted);
            }
            this.InvokeAsync("DajSifruStipendije", new object[] {
                        naziv}, this.DajSifruStipendijeOperationCompleted, userState);
        }
        
        private void OnDajSifruStipendijeOperationCompleted(object arg) {
            if ((this.DajSifruStipendijeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajSifruStipendijeCompleted(this, new DajSifruStipendijeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DajSveStipendijeCompletedEventHandler(object sender, DajSveStipendijeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajSveStipendijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajSveStipendijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DajStipendijuCompletedEventHandler(object sender, DajStipendijuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajStipendijuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajStipendijuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DajSifruStipendijeCompletedEventHandler(object sender, DajSifruStipendijeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajSifruStipendijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajSifruStipendijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591